const dashboardRoute = "/dashboard";

const router = {
  SIGNIN: "/login",
  REGISTER: "/register",
  SIGNUP: "/signup",
  CREATENEWPASSWORD: "/create-new-password",
  FORGOTPASSWORD: "/forgot-password",
  HOWITWORK: "/howitwork",
  CONTACTUS: "/contactus",
  ENQUIRY: "/enquiry",
  PROFILE: "/profile",
  HOME: "/",
  USERS: "/users",
  VENDERS: "/venders",
  ADMINLIST: "/adminList",
  HERO_BANNER: "/heroBanner",
  BLOGS: "/blogs",
  VENUE: "/venue",
  VENUE_LIST: "/venueList",
  VENUE_PLACE_LIST: "/venuePlaceList",
  EVENT_BOOK: "/eventbooking",
  VENUE_PLACE: "/venuePlace",
  VENUE_BEVERAGE: "/venue/beverage",
  VENUE_DISABLED: "/venue/disableFacility",
  VENUE_EQUIPMENT: "/venue/equipment",
  VENUE_EVENT: "/venue/event",
  VENUE_FACILITY: "/venue/facility",
  VENUE_LOCATION: "/venue/location",
  VENUE_LOCATION_CITY: "/venue/locationCity",
  VENUE_LOCATION_TYPE: "/venue/locationType",
  VENUE_MENU: "/venue/menu",
  VENUE_SERVICE: "/venue/service",
  NEWSLETTER: "/newsletter",
};
export default router;
