const dashboardRoute = "/dashboard";

const router = {
  SPLASH: "/splashscreen",
  SIGNIN: "/signin",
  REGISTER: "/register",
  SIGNUP: "/signup",
  ADDEMAIL: "/addemail",
  CREATENEWPASSWORD: "/create-new-password",
  FORGOTPASSWORD: "/forgot-password",
  USERNAME: "/username",
  BORNDATE: "/borndate",
  INVITE: "/invite",
  SHARELOCATION: "/sharelocation",
  USERPROFILE: "/uploadprofilepic",
  SIMPLERULES: "/simplerules",
  CATEGORIES: "/categories",
  HOWITWORKS: "/howitworks",
  HOWITWORK: "/howitwork",
  CONTACTUS: "/contactus",
  SEARCH: "/search",
  PEOPLE: "/people",
  REVIEW: "/review",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  POST: "/post",
  HOME: "/",
  FEED: "/feed",
  FOLLOWED: "/followed",
  RESETPASS: "/reset-password/[token]",
  PAYOUTPREFERENCES: "/payout-preferences",
  CHANGEPASS: "/change-password",
  FAQ: "/faq",
  ABOUT: "/about",
};
export default router;
